---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.vodafone.com
  resources:
  - podnotifrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.vodafone.com
  resources:
  - podnotifrestarts/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.vodafone.com
  resources:
  - podnotifrestarts/status
  verbs:
  - get
  - patch
  - update
