apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    matchLabels:
      app: pod-restart-notifier-operator
  template:
    metadata:
      labels:
        app: pod-restart-notifier-operator
    spec:
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: DISCORD_WEBHOOK_URL
          value: "{{ .Values.discord.webhookURL }}"
        - name: TEAMS_WEBHOOK_URL
          value: "{{ .Values.teams.webhookURL }}"
        - name: SLACK_WEBHOOK_URL
          value: "{{ .Values.slack.webhookURL }}"
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
